import type { Dynamic, RecordRow, SemaforoStatus, ValueFormat } from './types';
export const palette = ['#EB0029','#0066CC','#008744','#C59B27','#7C3AED','#E67E22','#0F766E','#D32F2F'];
export const statusColor: Record<SemaforoStatus, string> = { good:'#008744', warning:'#E67E22', bad:'#D32F2F', neutral:'#7A8290' };
export function pointer(source: unknown, path?: string): unknown { if (!path) return source; return path.replace(/^\//,'').split('/').filter(Boolean).reduce<unknown>((value, key) => value && typeof value === 'object' ? (value as Record<string, unknown>)[key.replace(/~1/g,'/').replace(/~0/g,'~')] : undefined, source); }
export function resolve<T>(value: Dynamic<T> | undefined, data?: Record<string, unknown>): T | undefined { if (value && typeof value === 'object') { const dynamicObj = value as { path?: string; value?: T }; if (dynamicObj.path) return pointer(data, dynamicObj.path) as T; if ('value' in dynamicObj) return dynamicObj.value; } return value as T | undefined; }
export function rows(data: Record<string, unknown> | undefined, path?: string): RecordRow[] { const result = pointer(data, path); return Array.isArray(result) ? result as RecordRow[] : []; }
export function num(value: unknown, fallback = 0) { const n = Number(value); return Number.isFinite(n) ? n : fallback; }
export function extent(values: unknown[]) { const list = values.map(v=>num(v, NaN)).filter(Number.isFinite); return [Math.min(...list,0), Math.max(...list,1)] as const; }
export function scale(value:number, domain:[number,number], range:[number,number]) { const [a,b]=domain; return range[0] + ((value-a)/(b-a || 1))*(range[1]-range[0]); }
export function format(value: unknown, kind: ValueFormat = 'number', currency='MXN') { const n=num(value); if (kind==='currency') return new Intl.NumberFormat('es-MX',{style:'currency',currency,minimumFractionDigits:2}).format(n); if(kind==='percent') return new Intl.NumberFormat('es-MX',{style:'percent',maximumFractionDigits:1}).format(n/100); if(kind==='date') return new Intl.DateTimeFormat('es-MX',{dateStyle:'medium'}).format(new Date(String(value))); return kind==='text' ? String(value ?? '') : new Intl.NumberFormat('es-MX',{maximumFractionDigits:2}).format(n); }
export function path(points:Array<[number,number]>) { return points.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(2)},${y.toFixed(2)}`).join(' '); }
export function arc(cx:number,cy:number,r:number,start:number,end:number,inner=0) { const p=(radius:number,angle:number)=>[cx+radius*Math.cos(angle),cy+radius*Math.sin(angle)]; const [x1,y1]=p(r,start),[x2,y2]=p(r,end), large=end-start>Math.PI?1:0; if(!inner)return `M${cx},${cy} L${x1},${y1} A${r},${r} 0 ${large} 1 ${x2},${y2} Z`; const [ix1,iy1]=p(inner,end),[ix2,iy2]=p(inner,start); return `M${x1},${y1} A${r},${r} 0 ${large} 1 ${x2},${y2} L${ix1},${iy1} A${inner},${inner} 0 ${large} 0 ${ix2},${iy2} Z`; }
