"""
Banking Data Security & Sanitization Module for Banorte Maya
Complies with PCI-DSS guidelines for handling Sensitive Authentication Data (SAD)
and Personally Identifiable Information (PII) before persisting to memory or LLM contexts.
"""
import re
from typing import Any, Dict, Optional

# Regular expressions for sensitive banking patterns
# 1. 15-16 digit card PANs (with optional spaces or dashes)
CARD_PAN_PATTERN = re.compile(r'\b(?:\d{4}[ -]?){3}\d{4}\b|\b(?:\d{4}[ -]?){2}\d{6}\b')

# 2. 18-digit Mexican CLABE accounts
CLABE_PATTERN = re.compile(r'\b\d{18}\b')

# 3. Sensitive tokens / OTP / passwords
TOKEN_PATTERNS = [
    re.compile(r'\b(?:token|otp|auth_token|clave|cvv|cvc)\s*[:=]?\s*["\']?([A-Za-z0-9_\-]{3,32})["\']?', re.IGNORECASE),
    re.compile(r'\b[0-9]{3,4}\b(?=\s*(?:cvv|cvc|código de seguridad))', re.IGNORECASE)
]

# 4. Basic prompt injection attempt signatures for memory poisoning prevention
PROMPT_INJECTION_PATTERNS = [
    re.compile(r'(?:ignore|olvida|deshaz|borra)\s+(?:all\s+)?(?:previous\s+)?(?:instructions|instrucciones|reglas)', re.IGNORECASE),
    re.compile(r'(?:system\s+prompt|eres\s+un\s+nuevo\s+modelo|act\s+as\s+a|actúa\s+como)', re.IGNORECASE)
]

def mask_card_number(pan_match: re.Match) -> str:
    raw = pan_match.group(0)
    digits = re.sub(r'\D', '', raw)
    if len(digits) >= 15:
        last4 = digits[-4:]
        return f"**** **** **** {last4}"
    return raw

def mask_clabe_number(clabe_match: re.Match) -> str:
    raw = clabe_match.group(0)
    last4 = raw[-4:]
    return f"*** *** ********** {last4}"

def sanitize_banking_message(text: str) -> str:
    """
    Sanitizes user or assistant message content before storage in SQLite:
    1. Masks credit/debit card numbers to last 4 digits.
    2. Masks CLABE numbers to last 4 digits.
    3. Redacts one-time OTP codes, tokens, and CVVs.
    4. Neutralizes prompt injection phrases from persistent memory strings.
    """
    if not text or not isinstance(text, str):
        return ""

    sanitized = text

    # Mask Card PANs
    sanitized = CARD_PAN_PATTERN.sub(mask_card_number, sanitized)

    # Mask CLABEs
    sanitized = CLABE_PATTERN.sub(mask_clabe_number, sanitized)

    # Redact Tokens and CVVs
    for pat in TOKEN_PATTERNS:
        sanitized = pat.sub(r'[DATO DE SEGURIDAD REDACTADO]', sanitized)

    return sanitized.strip()

def sanitize_memory_summary(summary: str) -> str:
    """
    Sanitizes memory consolidation snippets generated by the model before saving
    to user_cognitive_profile to prevent memory poisoning across sessions.
    """
    if not summary or not isinstance(summary, str):
        return ""

    cleaned = sanitize_banking_message(summary)

    for pat in PROMPT_INJECTION_PATTERNS:
        cleaned = pat.sub('[Instrucción bloqueada]', cleaned)

    return cleaned[:500]  # Limit length for memory entries
